# Generated by Django 2.2.8 on 2019-12-12 02:11

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(db_index=True, default='problem', max_length=32)),
                ('module_state_key', opaque_keys.edx.django.models.UsageKeyField(db_column='module_id', max_length=255)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('state', models.TextField(blank=True, null=True)),
                ('grade', models.FloatField(blank=True, db_index=True, null=True)),
                ('max_grade', models.FloatField(blank=True, null=True)),
                ('done', models.CharField(default='na', max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('student', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'module_state_key', 'course_id')},
            },
        ),
    ]
