# Generated by Django 2.2.17 on 2021-01-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_grades', '0002_auto_20190703_1526'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS djcelery_crontabschedule;"),
        migrations.RunSQL("DROP TABLE IF EXISTS djcelery_intervalschedule;"),
        migrations.RunSQL("DROP TABLE IF EXISTS djcelery_periodictask;"),
        migrations.RunSQL("DROP TABLE IF EXISTS djcelery_periodictasks;"),
        migrations.RunSQL("DROP TABLE IF EXISTS djcelery_taskmeta;"),
        migrations.RunSQL("DROP TABLE IF EXISTS djcelery_tasksetmeta;"),
        migrations.RunSQL("DROP TABLE IF EXISTS djcelery_taskstate;"),
        migrations.RunSQL("DROP TABLE IF EXISTS djcelery_workerstate;"),
    ]
